server:
    port: 9090
    context-path: #/liuzh/

logging:
    level:
        tk.mybatis: TRACE

druid:
  url: jdbc:mysql://127.0.0.1:3307/test
  username: root
  password: w123321
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true
spring:
    mvc:
        view:
            prefix: /templates/
            suffix: .html
    freemarker:
        cache: false
        request-context-attribute: request
        
mybatis:
    type-aliases-package: cn.tw.mongo.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - cn.tw.mongo.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql*/sss